CREATE TABLE pastes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(64),
    content    TEXT        NOT NULL,
    code       VARCHAR(32) NOT NULL UNIQUE,
    visibility VARCHAR(10) NOT NULL,
    status     VARCHAR(10) NOT NULL,
    expiration TIMESTAMP   NOT NULL
);